% drugPercent.m
% this script computes the visits where each of the eleven
% non-neuro drugs were taken as percentages of visits where
% the anti-AD drugs were taken (el 1) or not (el 2);
% the InRADC and InNACC matrces must be present in the workspace

% define percent function
percent = @(x)sum(x)/numel(x)*100;

% make drug subarray 
rDA = InRADC(:,11:27); % for RADC (drugs start at 11)
nDA = InNACC(:,21:37); % for NACC (drugs start at 21)

% remove all nonbinary values
rDA(find(rDA < 1)) = 0;
nDA(find(nDA < 1)) = 0;

% compute percentages 
RdrugPCT = splitapply(percent,rDA(:,1:16),findgroups(rDA(:,17)));
NdrugPCT = splitapply(percent,nDA(:,1:16),findgroups(nDA(:,17)));
RantiADPCT = percent(rDA(:,17))
NantiADPCT = percent(nDA(:,17))

% plot bars
figure(33)
clf
subplot(2,1,1)
bar(RdrugPCT')
title('ROSMAP Drug Use Percentages')
legend('no anti-AD','yes anti-AD','location','northwest')
text(3,3.45,'anti-AD use is 6%')
% set(gca,'Xticklabel',[])
xticks(1:16)
xticklabels({'NSAID',...
    'ACE I',...
    'ARBS',...
    'Ca chan B',...
    'beta B',...
    'diuretic',...
    'vasodil',...
    'anticoag',...
    'lipid low',...
    'antidiab',...
    'est/pro',...
    'anti-ad',...
    'antidep',...
    'antipsych',...
    'anxiolyt',...
    'anti-Park'})
xtickangle(-90)
ylabel('percentage drug use')
subplot(2,1,2)
bar(NdrugPCT')
title('NACC Drug Use Percentages')
legend('no anti-AD','yes anti-AD','location','northwest')
text(3,2.1,'anti-AD use is 27%')
xticks(1:16)
xticklabels({'NSAID',...
    'ACE I',...
    'ARBS',...
    'Ca chan B',...
    'beta B',...
    'diuretic',...
    'vasodil',...
    'anticoag',...
    'lipid low',...
    'antidiab',...
    'est/pro',...
    'anti-ad',...
    'antidep',...
    'antipsych',...
    'anxiolyt',...
    'anti-Park'})
xtickangle(-90)
ylabel('percentage drug use')



% xticks(1:17)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'ANG II R blockers',...
%     'Ca channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics',...
%     'estrogen or progest',...
%     'anti-adrenergics',...
%     'antidepressants',...
%     'antipsychotics',...
%     'anxiolytics',...
%     'anti-Parkinsons',...
%     'anti-Alzheimers'})
