% LSTMcorrelate.m
% this script correlates the potential potencies
% as estimated from the RADC and NACC databases
% both cmbPotRADC and cmbPotNACC must be in workspace

% set number of drugs in combos
% *** this must be the same as in LSTMcombo and LSTMcomboJob ***
numDrugs = 17;
% numDrugs = 16;
% numDrugs = 11;
% numDrugs = 10;

% find all the drug combinations
% redo this computation if comboArray no longer in workspace
numCombos  = 2^numDrugs; % number of combinations
cmbNUMBER  = (1:numCombos)'; % combination number vector
comboArray = rem(floor((cmbNUMBER - 1)*pow2(-(numDrugs-1):0)),2); % combos

% set the number to include in the best of lists
% numBest = 10;
numBest = numCombos;

% find correlation coefficinet between RADC and NACC potentials
[coefPot, probPot] = corrcoef(cmbPotRADC,cmbPotNACC);

% fit line to RADC vs NACC potential potencies
linePot = polyfit(cmbPotRADC,cmbPotNACC,1);
% generate values specified by this line
% ** here RADC is dependent variable **
RADCseries = linspace(-0.4,0.4,100);
NACCpredic = polyval(linePot,RADCseries);
% find projections of potential potency points onto linePot
slope = linePot(1); % slope of regression line
inter = linePot(2); % intercept of regression line
vecLine = [1,slope*1]'; % regression line as vector (zero intercept)
promat = (vecLine * vecLine') / (vecLine' * vecLine); % projection matrix
pzero = [0,inter]'; % point to translate line to origin
% make pzero into an array to translate all the points
pzeroTran = [pzero(1) * ones(1,numCombos) ; pzero(2) * ones(1,numCombos)];
% collect all pairs of potential potency points (cmbPotRADC,cmbPotNACC)
pointsPot = [cmbPotRADC,cmbPotNACC]';
% get projections of all points onto vector (intersept is zero)
vecPotProj = promat * pointsPot;
% get projections of all points onto line (intersept is inter)
linePotProj = promat * (pointsPot - pzeroTran) + pzeroTran;
% find lengths of all vectors in vecPotProj
lengthPot = sqrt(sum(vecPotProj .^ 2));
% sort vector lengths
[~,indxBest] = sort(lengthPot,'descend');
% sort the combinations according to joint RADC-NACC potential potency 
combosSortJOINT = comboArray(indxBest,:);
% report correlation results
% insert semicolons for LSTMcorrelJob
SlopeInt = linePot
Coeffish = coefPot(2,1)
Probabil = probPot(2,1)

% comment in for LSTMcorrelJob
% return

% fit line to NACC vs RADC potential potencies
linePot = polyfit(cmbPotNACC,cmbPotRADC,1);
% generate values specified by this line
% ** here NACC is dependent variable **
NACCseries = linspace(-0.4,0.4,100);
RADCpredic = polyval(linePot,NACCseries);
% find projections of potential potency points onto linePot
slope = linePot(1); % slope of regression line
inter = linePot(2); % intercept of regression line
vecLine = [1,slope*1]'; % regression line as vector (zero intercept)
promat = (vecLine * vecLine') / (vecLine' * vecLine); % projection matrix
pzero = [0,inter]'; % point to translate line to origin
% make pzero into an array to translate all the points
pzeroTran = [pzero(1) * ones(1,numCombos) ; pzero(2) * ones(1,numCombos)];
% collect all pairs of potential potency points (cmbPotRADC,cmbPotNACC)
pointsPotRev = [cmbPotNACC,cmbPotRADC]';
% get projections of all points onto vector (intersept is zero)
vecPotProj = promat * pointsPotRev;
% get projections of all points onto line (intersept is inter)
linePotProjRev = promat * (pointsPotRev - pzeroTran) + pzeroTran;
% find lengths of all vectors in vecPotProj
lengthPot = sqrt(sum(vecPotProj .^ 2));
% sort vector lengths
[~,indxBestRev] = sort(lengthPot,'descend');
% sort the combinations according to joint RADC-NACC potential potency 
combosSortJOINTrev = comboArray(indxBest,:);
% report correlation results
SlopeIntRev = linePot
CoeffishRev = coefPot(2,1)
ProbabilRev = probPot(2,1)

% find correlations among sorted combinations
% [rhoPot probPot] = corr(combosSorted(1:numBest,:));
% corrNonSigIndx = find(probPot >= 0.01);
% rhoPot(corrNonSigIndx) = 0;
% rhoPot

% show numBest sorted combos
% combosSorted(1:numBest,:)
% sum(combosSorted(1:numBest,:)')
% mean(sum(combosSorted(1:numBest,:)'))

% find best combos using RADC or NACC alone
[~,indxBestRADC] = sort(cmbPotRADC,'descend');
[~,indxBestNACC] = sort(cmbPotNACC,'descend');
combosSortRADC = comboArray(indxBestRADC,:);
combosSortNACC = comboArray(indxBestNACC,:);

% find best combos in terms of sum of RADC and NACC potencies
cmbPotSUM = cmbPotRADC + cmbPotNACC;
[~,indxBestSUM] = sort(cmbPotSUM,'descend');
combosSortSUM = comboArray(indxBestSUM,:);

% find best combos in terms of sum of RADC and NACC rankings
% (note: RADC and NACC potencies are resorted in ascending order)
[~,indxBestRADC] = sort(cmbPotRADC);
[~,indxBestNACC] = sort(cmbPotNACC);
[~,ranksRADC] = sort(indxBestRADC);
[~,ranksNACC] = sort(indxBestNACC);
ranksSUM = ranksRADC + ranksNACC;
[~,indxBestRANK] = sort(ranksSUM,'descend');
combosSortRANK = comboArray(indxBestRANK,:);

% get some nice axis bounds
xLow  = min(cmbPotRADC) - 0.01;
xHigh = max(cmbPotRADC) + 0.01;
yLow  = min(cmbPotNACC) - 0.01;
yHigh = max(cmbPotNACC) + 0.01;

% plot regression 
figure(9)
clf
plot(cmbPotRADC,cmbPotNACC,'.b','markersize',8)
% plot(cmbPotRADC,cmbPotNACC,'.b','markersize',0.5)
% plot(cmbPotRADC,cmbPotNACC,'.b')
hold on
plot(RADCseries,NACCpredic,'r','linewidth',2)
% plot(cmbPotRADC(indxBestSUM(1:numBest)),...
%     cmbPotNACC(indxBestSUM(1:numBest)),...
%     'om','markersize',10,'linewidth',2)
% plot(cmbPotRADC(indxBestRANK(1:numBest)),...
%     cmbPotNACC(indxBestRANK(1:numBest)),...
%     'xc','markersize',10,'linewidth',2)
% plot([pointsPot(1,indxBest(1)) linePotProj(1,indxBest(1))],...
%      [pointsPot(2,indxBest(1)) linePotProj(2,indxBest(1))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(2)) linePotProj(1,indxBest(2))],...
%      [pointsPot(2,indxBest(2)) linePotProj(2,indxBest(2))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(3)) linePotProj(1,indxBest(3))],...
%      [pointsPot(2,indxBest(3)) linePotProj(2,indxBest(3))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(4)) linePotProj(1,indxBest(4))],...
%      [pointsPot(2,indxBest(4)) linePotProj(2,indxBest(4))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(5)) linePotProj(1,indxBest(5))],...
%      [pointsPot(2,indxBest(5)) linePotProj(2,indxBest(5))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(6)) linePotProj(1,indxBest(6))],...
%      [pointsPot(2,indxBest(6)) linePotProj(2,indxBest(6))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(7)) linePotProj(1,indxBest(7))],...
%      [pointsPot(2,indxBest(7)) linePotProj(2,indxBest(7))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(8)) linePotProj(1,indxBest(8))],...
%      [pointsPot(2,indxBest(8)) linePotProj(2,indxBest(8))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(9)) linePotProj(1,indxBest(9))],...
%      [pointsPot(2,indxBest(9)) linePotProj(2,indxBest(9))],...
%     '-g','linewidth',2)  
% plot([pointsPot(1,indxBest(10)) linePotProj(1,indxBest(10))],...
%      [pointsPot(2,indxBest(10)) linePotProj(2,indxBest(10))],...
%     '-g','linewidth',2)  
hold off
axis square
axis([xLow,xHigh,yLow,yHigh])
xlabel('ROSMAP scrambled','fontsize',11,'fontweight','bold')
ylabel('NACC scrambled','fontsize',11,'fontweight','bold')
% title('All Res, LSTM 80, Drugs 10, MinSeq 10',...
%     'fontsize',11,'fontweight','bold')
% title('Correlation between RADC and NACC Predicted Potencies',...
%     'fontsize',11,'fontweight','bold')
textX = xLow + 0.04;
textY = yLow + 0.005;
% text(textX,textY+0.008,'s = 0.??','fontsize',11,'fontweight','bold')
text(textX,textY+0.002,'r = 0.07','fontsize',11,'fontweight','bold')
text(textX,textY+0.000,'p = 0.02','fontsize',11,'fontweight','bold')
set(gca,'fontsize',11,'fontweight','bold')
set(gca,'linewidth',1)

% plot regression 
figure(10)
clf
% plot(cmbPotNACC,cmbPotRADC,'.b','markersize',8)
plot(cmbPotNACC,cmbPotRADC,'.b','markersize',0.5)
% plot(cmbPotNACC,cmbPotRADC,'.b')
hold on
plot(NACCseries,RADCpredic,'r','linewidth',2)
% plot(cmbPotNACC(indxBestSUM(1:numBest)),...
%     cmbPotRADC(indxBestSUM(1:numBest)),...
%     'om','markersize',10,'linewidth',2)
% plot(cmbPotNACC(indxBestRANK(1:numBest)),...
%     cmbPotRADC(indxBestRANK(1:numBest)),...
%     'xc','markersize',10,'linewidth',2)
% plot([pointsPotRev(1,indxBestRev(1)) linePotProjRev(1,indxBestRev(1))],...
%      [pointsPotRev(2,indxBestRev(1)) linePotProjRev(2,indxBestRev(1))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(2)) linePotProjRev(1,indxBestRev(2))],...
%      [pointsPotRev(2,indxBestRev(2)) linePotProjRev(2,indxBestRev(2))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(3)) linePotProjRev(1,indxBestRev(3))],...
%      [pointsPotRev(2,indxBestRev(3)) linePotProjRev(2,indxBestRev(3))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(4)) linePotProjRev(1,indxBestRev(4))],...
%      [pointsPotRev(2,indxBestRev(4)) linePotProjRev(2,indxBestRev(4))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(5)) linePotProjRev(1,indxBestRev(5))],...
%      [pointsPotRev(2,indxBestRev(5)) linePotProjRev(2,indxBestRev(5))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(6)) linePotProjRev(1,indxBestRev(6))],...
%      [pointsPotRev(2,indxBestRev(6)) linePotProjRev(2,indxBestRev(6))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(7)) linePotProjRev(1,indxBestRev(7))],...
%      [pointsPotRev(2,indxBestRev(7)) linePotProjRev(2,indxBestRev(7))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(8)) linePotProjRev(1,indxBestRev(8))],...
%      [pointsPotRev(2,indxBestRev(8)) linePotProjRev(2,indxBestRev(8))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(9)) linePotProjRev(1,indxBestRev(9))],...
%      [pointsPotRev(2,indxBestRev(9)) linePotProjRev(2,indxBestRev(9))],...
%     '-g','linewidth',2)  
% plot([pointsPotRev(1,indxBestRev(10)) linePotProjRev(1,indxBestRev(10))],...
%      [pointsPotRev(2,indxBestRev(10)) linePotProjRev(2,indxBestRev(10))],...
%     '-g','linewidth',2)  
hold off
axis square
axis([yLow,yHigh,xLow,xHigh ])
xlabel('NACC scrambled','fontsize',11,'fontweight','bold')
ylabel('ROSMAP scrambled','fontsize',11,'fontweight','bold')
% title('All Res, LSTM 80, Drugs 10, MinSeq 10, Reversed',...
%     'fontsize',11,'fontweight','bold')
% title('Correlation between RADC and NACC Predicted Potencies',...
%     'fontsize',11,'fontweight','bold')
textX = -0.015;
textY = -0.20;
% text(textX,textY+0.016,'s = 0.93','fontsize',11,'fontweight','bold')
text(textX,textY+0.015,'r = 0.07','fontsize',11,'fontweight','bold')
text(textX,textY+0.000,'p = 0.02','fontsize',11,'fontweight','bold')
set(gca,'fontsize',11,'fontweight','bold')
set(gca,'linewidth',1)

% comment out to see heat maps
% return

% view sorted combinations as a heat map
figure(11)
clf
imagesc(combosSortJOINT(1:numBest,:))

xticks(1:17)
xticklabels({'non-steroidals',...
    'ACE inhibiors',...
    'ANG II R blockers',...
    'Ca channel blockers',...
    'beta blockers',...
    'diuretics',...
    'vasodilators',...
    'anticoagulants',...
    'lipid lowerers',...
    'antidiabetics',...
    'estrogen or progest',...
    'anti-adrenergics',...
    'antidepressants',...
    'antipsychotics',...
    'anxiolytics',...
    'anti-Parkinsons',...
    'anti-Alzheimers'})

% xticks(1:16)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'ANG II R blockers',...
%     'Ca channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics',...
%     'estrogen or progest',...
%     'anti-adrenergics',...
%     'antidepressants',...
%     'antipsychotics',...
%     'anxiolytics',...
%     'anti-Parkinsons'})

% xticks(1:11)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'angiotnesin IIR blockers',...
%     'calcium channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics',...
%     'estrogen or progestin'})

% xticks(1:10)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'ANG II R blockers',...
%     'Ca channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics'})

xtickangle(-90)
% set y ticks for ten-bests only
% yticks(1:10)
ylabel('rank-ordered combinations')
% title('Drug Combinations ranked by Predicted Potency')
% title('All Ins Res, LSTM 80, Drugs 10, MinSeq 10')
set(gca,'fontsize',11,'fontweight','bold')

% *** plot the dubalows! ***
% comment out the following to not show
return

figure(15)
clf
subplot(1,2,1)
% plot(cmbPotRADC,cmbPotNACC,'.b','markersize',8)
plot(cmbPotRADC,cmbPotNACC,'.b','markersize',0.5)
% plot(cmbPotRADC,cmbPotNACC,'.b')
hold on
plot(RADCseries,NACCpredic,'r','linewidth',2)
plot(cmbPotRADC(indxBestSUM(1:numBest)),...
    cmbPotNACC(indxBestSUM(1:numBest)),...
    'om','markersize',9,'linewidth',2)
plot(cmbPotRADC(indxBestRANK(1:numBest)),...
    cmbPotNACC(indxBestRANK(1:numBest)),...
    'xc','markersize',9,'linewidth',2)
plot([pointsPot(1,indxBest(1)) linePotProj(1,indxBest(1))],...
     [pointsPot(2,indxBest(1)) linePotProj(2,indxBest(1))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(2)) linePotProj(1,indxBest(2))],...
     [pointsPot(2,indxBest(2)) linePotProj(2,indxBest(2))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(3)) linePotProj(1,indxBest(3))],...
     [pointsPot(2,indxBest(3)) linePotProj(2,indxBest(3))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(4)) linePotProj(1,indxBest(4))],...
     [pointsPot(2,indxBest(4)) linePotProj(2,indxBest(4))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(5)) linePotProj(1,indxBest(5))],...
     [pointsPot(2,indxBest(5)) linePotProj(2,indxBest(5))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(6)) linePotProj(1,indxBest(6))],...
     [pointsPot(2,indxBest(6)) linePotProj(2,indxBest(6))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(7)) linePotProj(1,indxBest(7))],...
     [pointsPot(2,indxBest(7)) linePotProj(2,indxBest(7))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(8)) linePotProj(1,indxBest(8))],...
     [pointsPot(2,indxBest(8)) linePotProj(2,indxBest(8))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(9)) linePotProj(1,indxBest(9))],...
     [pointsPot(2,indxBest(9)) linePotProj(2,indxBest(9))],...
    '-g','linewidth',2)  
plot([pointsPot(1,indxBest(10)) linePotProj(1,indxBest(10))],...
     [pointsPot(2,indxBest(10)) linePotProj(2,indxBest(10))],...
    '-g','linewidth',2)  
hold off
axis square
axis([xLow,xHigh,yLow,yHigh])
xlabel('ROSMAP scrambled','fontsize',11,'fontweight','bold')
ylabel('NACC scrambled','fontsize',11,'fontweight','bold')
textX = xLow + 0.04;
textY = yLow + 0.005;
% text(textX,textY+0.008,'s = 0.22','fontsize',11,'fontweight','bold')
text(textX,textY+0.004,'r = 0.07','fontsize',11,'fontweight','bold')
text(textX,textY+0.000,'p = 0.02','fontsize',11,'fontweight','bold')
Ax = xLow - 0.001;
Ay = yHigh + 0.002;
text(Ax,Ay,'A','fontsize',14,'fontweight','bold')
set(gca,'fontsize',11,'fontweight','bold')
set(gca,'linewidth',1)

subplot(1,2,2)
imagesc(combosSortJOINT(1:numBest,:))
axis square

% xticks(1:17)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'ANG II R blockers',...
%     'Ca channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics',...
%     'estrogen or progest',...
%     'anti-adrenergics',...
%     'antidepressants',...
%     'antipsychotics',...
%     'anxiolytics',...
%     'anti-Parkinsons',...
%     'anti-Alzheimers'})

% xticks(1:16)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'ANG II R blockers',...
%     'Ca channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics',...
%     'estrogen or progest',...
%     'anti-adrenergics',...
%     'antidepressants',...
%     'antipsychotics',...
%     'anxiolytics',...
%     'anti-Parkinsons'})

% xticks(1:11)
% xticklabels({'non-steroidals',...
%     'ACE inhibiors',...
%     'ANG II R blockers',...
%     'Ca channel blockers',...
%     'beta blockers',...
%     'diuretics',...
%     'vasodilators',...
%     'anticoagulants',...
%     'lipid lowerers',...
%     'antidiabetics',...
%     'estrogen or progest'})

xticks(1:10)
xticklabels({'non-steroidals',...
    'ACE inhibiors',...
    'ANG II R blockers',...
    'Ca channel blockers',...
    'beta blockers',...
    'diuretics',...
    'vasodilators',...
    'anticoagulants',...
    'lipid lowerers',...
    'antidiabetics'})

xtickangle(-90)
% set y ticks for ten-bests only
yticks(1:10)
ylabel('rank-ordered combinations')
text(-0.02,-0.1,'B','fontsize',14,'fontweight','bold')
set(gca,'fontsize',11,'fontweight','bold')

% note: the following are all for combos of 10 drugs only
% comment in the return if they are not needed
% return

% compare numBest sorted combos between
% RADC alone, NACC alone, and joint RADC dependent
% this is for 10 drug combos only
figure(12)
clf
subplot(3,1,1)
imagesc(combosSortRADC(1:numBest,:))
title('ROSMAP Alone Top Ten Combos')
yticks(1:10)
set(gca,'Xticklabel',[])
set(gca,'fontsize',11,'fontweight','bold')
subplot(3,1,2)
imagesc(combosSortNACC(1:numBest,:))
title('NACC Alone Top Ten Combos')
set(gca,'Xticklabel',[])
yticks(1:10)
ylabel('rank-ordered combinations')
set(gca,'fontsize',11,'fontweight','bold')
subplot(3,1,3)
imagesc(combosSortJOINT(1:numBest,:))
title('NACC(ROSMAP) Regression Top Ten Combos')
yticks(1:10)
xticks(1:10)
xticklabels({'NSAIDs',...
    'ACE Is',...
    'ANGIIR Bs',...
    'Ca Ch Bs',...
    'beta Bs',...
    'diuret',...
    'vasodil',...
    'anticos',...
    'lip lows',...
    'antidibs'})
xtickangle(-90)
set(gca,'fontsize',11,'fontweight','bold')

% compare numBest sorted combos between
% sum, rank sum, and joint RADC dep
% this is for 10 drug combos only
figure(13)
clf
subplot(3,1,1)
imagesc(combosSortSUM(1:numBest,:))
title('ROSMAP + NACC SUM Top Ten Combos')
yticks(1:10)
set(gca,'Xticklabel',[])
set(gca,'fontsize',11,'fontweight','bold')
subplot(3,1,2)
imagesc(combosSortRANK(1:numBest,:))
title('ROSMAP + NACC RANK SUM Top Ten Combos')
set(gca,'Xticklabel',[])
yticks(1:10)
ylabel('rank-ordered combinations')
set(gca,'fontsize',11,'fontweight','bold')
subplot(3,1,3)
imagesc(combosSortJOINT(1:numBest,:))
title('NACC(ROSMAP) Regression Top Ten Combos')
yticks(1:10)
xticks(1:10)
xticklabels({'NSAIDs',...
    'ACE Is',...
    'ANGIIR Bs',...
    'Ca Ch Bs',...
    'beta Bs',...
    'diuret',...
    'vasodil',...
    'anticos',...
    'lip lows',...
    'antidibs'})
xtickangle(-90)
set(gca,'fontsize',11,'fontweight','bold')

% compare numBest sorted combos between
% joint NACC dep and joint RADC dep
% this is for 10 drug combos only
figure(14)
clf
subplot(2,1,1)
imagesc(combosSortJOINTrev(1:numBest,:))
title('ROSMAP(NACC) Regression Top Ten Combos')
set(gca,'Xticklabel',[])
yticks(1:10)
ylabel('ranked combs')
set(gca,'fontsize',11,'fontweight','bold')
subplot(2,1,2)
imagesc(combosSortJOINT(1:numBest,:))
title('NACC(ROSMAP) Regression Top Ten Combos')
xticks(1:10)
xticklabels({'NSAIDs',...
    'ACE Is',...
    'ANGIIR Bs',...
    'Ca Ch Bs',...
    'beta Bs',...
    'diuret',...
    'vasodil',...
    'anticos',...
    'lip lows',...
    'antidibs'})
xtickangle(-90)
yticks(1:10)
ylabel('ranked combos')
set(gca,'fontsize',11,'fontweight','bold')





