% NACCreadDataset.m
% this script reads the whole NACC dataset;
% the CSV rather than the XLS file is read;
% the CSV file is read into a table in MATLAB;
% only certain columns are then selected

% start the timer
tic

% read all text and numerical data from NACCdataset21Oct2019.csv
% into a table
% naccTable = readtable('NACCdataset.csv');
% naccTable = readtable('NACCdatasetNoRADC.csv');
% naccTable = readtable('NACCdataset21Oct2019.csv');
naccTable = readtable('NACCdataOct2019noRADC.csv');

% the following was used for Ver1 and Ver2 
% naccTable = readtable('NACCdataset.csv'); % same as 21Oct2019 version

% hold naccTable as a debug
% naccTableHold = naccTable;

% get all column headings
% (needed only to change variable inclusions)
% vNamesAll = naccTable.Properties.VariableNames';

% reset naccTable as a debug
% naccTable = naccTableHold;

% take only certain columns
% NACC dataset curated to reduce redundancies, and to exclude
% variable types that are not present in RADC or CADRD;
% variables excluded here include imaging, biomarkers, genetics
naccTable = naccTable(:,{...
    'NACCID',...   % ID number
    'NACCAGE',...  % age variables
    'VISITMO',...
    'VISITYR',...
    'BIRTHMO',...
    'BIRTHYR',...
    'NACCYOD',...
    'SEX',...      % demographics
    'HISPANIC',...
    'RACE',...
    'EDUC',...
    'HEIGHT',...   % physical exam
    'WEIGHT',...
    'NACCBMI',...
    'BPSYS',...
    'BPDIAS',...
    'HRATE',...
    'TOBAC30',...  % tobacco/alcohol/drugs
    'TOBAC100',...
    'SMOKYRS',...
    'PACKSPER',...
    'QUITSMOK',...
    'ALCOCCAS',...
    'ALCFREQ',...
    'ALCOHOL',...
    'ABUSOTHR',...
    'NACCNSD',...  % medications
    'NACCACEI',...
    'NACCANGI',...
    'NACCCCBS',...
    'NACCBETA',...
    'NACCDIUR',...
    'NACCVASD',...
    'NACCAC',...
    'NACCLIPL',...
    'NACCDBMD',...
    'NACCEPMD',...
    'NACCAAAS',...
    'NACCADEP',...
    'NACCAPSY',...
    'NACCAANX',...
    'NACCPDMD',...
    'NACCADMD',...
    'ANYMEDS',...
    'NACCAMD',...
    'NACCAHTN',...
    'NACCHTNC',...
    'NACCEMD',...
    'CVHATT',...   % comorbidities
    'CVAFIB',...
    'CVANGIO',...
    'CVBYPASS',...
    'CVPACDEF',...
    'CVCHF',...
    'CVANGINA',...
    'CVHVALVE',...
    'CBSTROKE',...
    'CBTIA',...
    'PD',...
    'PDOTHR',...
    'SEIZURES',...
    'TBI',...
    'TBIBRIEF',...
    'TBIEXTEN',...
    'TRAUMEXT',...
    'TBIWOLOS',...
    'DIABETES',...
    'HYPERTEN',...
    'HYPERCHO',...
    'B12DEF',...
    'THYROID',...
    'ARTHRIT',...
    'APNEA',...
    'RBD',...
    'INSOMN',...
    'PTSD',...
    'BIPOLAR',...
    'SCHIZ',...
    'DEP2YRS',...
    'DEPOTHR',...
    'ANXIETY',...
    'OCD',...
    'NPSYDEV',...
    'HIV',...
    'CANCER',...
    'DEMENTED',... % dementia diagnosis
    'AMNDEM',...
    'NACCBVFT',...
    'NACCLBDS',...
    'NAMNDEM',...
    'NACCTMCI',...
    'IMPNOMCI',...
    'NACCALZD',...
    'PROBAD',... 
    'PROBADIF',...
    'POSSAD',...
    'POSSADIF',...
    'NACCLBDE',...
    'NACCLBDP',...
    'FTD',...
    'FTDIF',...
    'VASC',...
    'VASCIF',...
    'VASCPS',...
    'HIVIF',...
    'MEDS',...
    'MEDSIF',...
    'NACCMMSE',... % mental/cognitive tests
    'LOGIMEM',...
    'MEMUNITS',...
    'UDSBENTC',...
    'UDSBENTD',...
    'UDSBENRS',...
    'DIGIF',...
    'DIGIFLEN',...
    'DIGIB',...
    'DIGIBLEN',...
    'ANIMALS',...
    'VEG',...
    'TRAILA',...
    'TRAILARR',...
    'TRAILALI',...
    'TRAILB',...
    'TRAILBRR',...
    'TRAILBLI',...
    'WAIS',...
    'BOSTON',...
    'UDSVERFC',...
    'UDSVERFN',...
    'UDSVERNF',...
    'UDSVERLC',...
    'UDSVERLR',...
    'UDSVERLN',...
    'UDSVERTN',...
    'UDSVERTE',...
    'UDSVERTI',...
    'COGSTAT',...
    'MOCATOTS',...
    'MOCATRAI',...
    'MOCACUBE',...
    'MOCACLOC',...
    'MOCACLON',...
    'MOCACLOH',...
    'MOCANAMI',...
    'MOCAREGI',...
    'MOCADIGI',...
    'MOCALETT',...
    'MOCASER7',...
    'MOCAREPE',...
    'MOCAFLUE',...
    'MOCAABST',...
    'MOCARECN',...
    'MOCARECC',...
    'MOCARECR',...
    'MOCAORDT',...
    'MOCAORMO',...
    'MOCAORYR',...
    'MOCAORDY',...
    'MOCAORPL',...
    'MOCAORCT',...
    'CRAFTVRS',...
    'CRAFTURS',...
    'CRAFTDVR',...
    'CRAFTDRE',...
    });

% save NACC table at this stage as a debug
naccTableRaw = naccTable;

% get reduced set of column headings after curation
vNamesCurated = naccTable.Properties.VariableNames';
CnamesNACC = vNamesCurated;

% stop timer, report elapsed time
toc

% show first 10 rows of table as debug
% head(naccTable,10)


